---
include:
  - project: "adas/devops/images/common-ci"
    ref: "master"
    file: "/main.yml"
  - project: 'adas/devops/gitlab-remote-includes'
    ref: master
    file:
      - '/templates/helm.yml'


stages:
  - "lint"
  - "build"
  - "scan"
  - "diff"
  - "deploy"
  - "rollback"

variables:
  DEPLOY_IMAGE_NAME: "gitlab-token-exporter"
  DEPLOY_PROJECT_NAME: "infra"
  DEPLOY_IMAGE_REGISTRY: "${DOCKER_REGISTRY}"
  GITLAB_URL: "https://gitlab.int.e-kama.com"
  GROUP_ID: "160"
  ACCESS_TOKEN: "$ACCESS_TOKEN" 
  # Переменные для Kubeconfig
  KUBE_CONFIG_BASE64: "$KUBECONFIG_ADAS_INFRA_INT"
  KUBE_NAMESPACE: "gitlab-token-exporter"
  # Переменные для Helm
  HELM_IS_USE_LOCAL_REPO: "true"
  HELM_VALUES_FILE: "${CI_PROJECT_DIR}/.helm/values.yaml"
  HELM_RELEASE_NAME: "gitlab-token-exporter"
  HELM_SET: ""
  DEPLOY_IMAGE_TAG: "latest"

before_script: []

.default_helm_rules:
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: manual
    - when: never


.build:test-image:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never

.build:release-image:
  stage: build
  variables:
    DEPLOY_IMAGE_TAG: "${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_IMAGE_TAG: "${CI_COMMIT_BRANCH}"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_IMAGE_TAG: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"

check-dockle:
  stage: scan
  variables:
    DEPLOY_IMAGE_TAG: "${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG'
      variables:
        DEPLOY_IMAGE_TAG: "${CI_COMMIT_TAG}"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_IMAGE_TAG: "${CI_COMMIT_BRANCH}"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_IMAGE_TAG: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"

scan-trivy:
  stage: scan
  variables:
    DEPLOY_IMAGE_TAG: "${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG'
      variables:
        DEPLOY_IMAGE_TAG: "${CI_COMMIT_TAG}"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_IMAGE_TAG: "${CI_COMMIT_BRANCH}"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_IMAGE_TAG: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"

lint::infra-common:
  stage: lint
  extends: .helm_lint

diff::infra-common:
  stage: diff
  before_script:
    - echo "${KUBE_CONFIG_BASE64}" | base64 -d > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
    - helm plugin install https://github.com/databus23/helm-diff
  extends: [.helm_diff]

helm_deploy:
  stage: deploy
  variables:
    HELM_SET: "image.tag=${CI_COMMIT_TAG}"
  before_script:
    - echo "${KUBE_CONFIG_BASE64}" | base64 -d > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
    - 'echo "Helm settings: $HELM_SET"'
  script:
    - |
      if [ "${HELM_IS_USE_LOCAL_REPO}" = "true" ]; then
        helm upgrade --install $HELM_RELEASE_NAME $HELM_DIR \
          --namespace $KUBE_NAMESPACE \
          --create-namespace \
          $HELM_SET
      else
        helm repo add $HELM_REPO_NAME $HELM_REPO_URL && \
        helm upgrade --install \
          -f $HELM_VALUES_FILE \
          $HELM_RELEASE_NAME $HELM_CHART \
          --namespace $KUBE_NAMESPACE \
          --version $HELM_VERSION \
          --create-namespace \
          $HELM_SET
      fi
  extends: [.default_helm_rules]

helm_rollback:
  stage: rollback
  before_script:
    - echo "${KUBE_CONFIG_BASE64}" | base64 -d > kubeconfig
    - export KUBECONFIG=$CI_PROJECT_DIR/kubeconfig
  script:
    >-
      helm rollback $HELM_RELEASE_NAME -n $KUBE_NAMESPACE
  extends: [.default_helm_rules]